# Generated by Django 5.2.6 on 2025-09-28 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(blank=True, max_length=80, null=True)),
                ('pais', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('edificio', 'Edificio'), ('condominio', 'Condominio'), ('complejo', 'Complejo'), ('otro', 'Otro')], max_length=30, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'propiedades',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nivel', models.CharField(blank=True, max_length=30, null=True)),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('propiedad', models.ForeignKey(db_column='propiedad_id', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='propiedades.propiedad')),
            ],
            options={
                'db_table': 'unidades',
                'constraints': [models.UniqueConstraint(fields=('propiedad', 'codigo'), name='uniq_propiedad_codigo')],
            },
        ),
    ]
