# Generated by Django 5.2.6 on 2025-09-28 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=60, null=True)),
                ('modelo', models.CharField(blank=True, max_length=60, null=True)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('unidad', models.ForeignKey(db_column='unidad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='propiedades.unidad')),
                ('usuario', models.ForeignKey(db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
    ]
